# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’

source 'https://github.com/CocoaPods/Specs.git'
target ‘SuperPlay’ do
    
    use_frameworks!
    
    pod 'TXLiteAVSDK_Professional'
    pod 'Masonry'
    pod 'AFNetworking'
    pod 'MMLayout'
    
    
    pod 'LeoDanmakuKit'
end
